server:
  port: 8080
  context-path: /sdk-server  
  tomcat.uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB 
  dubbo:
    applicationName: sdkweb
    address: zookeeper://192.168.184.130:2181
    timeout: 30000
    retries: 2           